### PR TITLE
Fixed "cannot self:_resolve_space(space)" in update function

### LINKED ISSUE #8: update error
Space **ipr** exist

Code:
```
tarantool = require("tarantool")
local tar = tarantool({
    host           = '127.0.0.1',
    port           = 3301,
    user           = 'user',
    password       = 'secret',
    socket_timeout = 2000,
    connect_now    = true,
})
local data, err = tar:update('ipr', 1, {{ '=', 3, 0 }})
tar:disconnect()
```
Error:
```
/usr/bin/lua: /usr/share/lua/5.3/tarantool.lua:317: attempt to concatenate a nil value (local 'space')
stack traceback:
        /usr/share/lua/5.3/tarantool.lua:317: in method '_resolve_space'
        /usr/share/lua/5.3/tarantool.lua:235: in method 'update'
        ./test_tar.lua:22: in main chunk
        [C]: in ?
```

Code:
```
tarantool = require("tarantool")
local tar = tarantool({
    host           = '127.0.0.1',
    port           = 3301,
    user           = 'user',
    password       = 'secret',
    socket_timeout = 2000,
    connect_now    = true,
})
local data,err = tar:select('ipr',0,1)
print(table.concat(data[1], ", "))
tar:disconnect()
```
Answer:
`1, test, 0, W`

What am I doing wrong?

### PR DESCRIPTION
**Pull request by zharkov-eu**
In update function somebody missed pass argument space, which was the cause of the error on update

Fixes #8

### CODE REVIEW

File: tarantool.lua [hunk 1]
```diff
@@ -241,7 +241,7 @@ do
         return response.data
       end
     end,
-    update = function(self, index, key, oplist)
+    update = function(self, space, index, key, oplist)
```
Comment (Totktonada) [inline tarantool.lua:234]: The change looks correct, but shouldn't we update the `tarantool.moon` file and regererate `tarantool.lua` to keep them in sync?

Comment (Totktonada) [reply tarantool.lua:234]: Updated `tarantool.moon` and regenerated `tarantool.lua`.

**Review by Totktonada — APPROVED** [review]
Tested manually. I confirm the problem and confirm the fix.

Rebased to current `master`, updated `tarantool.moon`, regenerated `tarantool.lua`, linked #8.
